# Generated by Django 2.0.7 on 2019-04-27 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('distancia', models.FloatField(default=0)),
                ('estacion_anterior', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lineas.Estaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('ubicacion', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='estaciones',
            name='linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estaciones', to='lineas.Linea'),
        ),
    ]
